export enum TypeFeed {
  COMMUNITY = 'community',
  ORIGINAL = 'original',
  NEWS = 'news',
  DESIGN = 'design',
  DATA_SCIENCE = 'data_science',
  DEVOPS = 'devops',
  CYBER_SECURITY = 'cyber_security',
  MIXED_REALITY = 'mixed_reality',
  CRYPTO_CURRENCY = 'crypto_currency',
  IOT = 'iot',
  MACHINE_LEARNING = 'machine_learning',
  SOFTWARE_ENGINEERING = 'software_engineering',
  FRONT_END_DEVELOPMENT = 'front_end_development',
  BACK_END_DEVELOPMENT = 'back_end_development',
  MOBILE_DEVELOPMENT = 'mobile_development',
}

export const contentTypeSourceBlog = {
  [TypeFeed.COMMUNITY]: 'Community',
  [TypeFeed.ORIGINAL]: 'Original',
  [TypeFeed.NEWS]: 'News',
  [TypeFeed.DESIGN]: 'Design',
  [TypeFeed.DATA_SCIENCE]: 'Data Science',
  [TypeFeed.DEVOPS]: 'DevOps',
  [TypeFeed.CYBER_SECURITY]: 'Cyber Security',
  [TypeFeed.MIXED_REALITY]: 'Mixed Reality',
  [TypeFeed.CRYPTO_CURRENCY]: 'Crypto Currency',
  [TypeFeed.IOT]: 'IoT',
  [TypeFeed.MACHINE_LEARNING]: 'Machine Learning',
  [TypeFeed.SOFTWARE_ENGINEERING]: 'Software Engineering',
  [TypeFeed.FRONT_END_DEVELOPMENT]: 'Front End Development',
  [TypeFeed.BACK_END_DEVELOPMENT]: 'Back End Development',
  [TypeFeed.MOBILE_DEVELOPMENT]: 'Mobile Development',
};
