export enum LocalStorageKeysEnums {
  LIST_CATEGORY_AI_TOOLS = 'LIST_CATEGORY_AI_TOOLS',
  AI_TOOL_INFO_ON_LOAD = 'AI_TOOL_INFO_ON_LOAD',
  AI_TOOL_CATEGORIES_MAP = 'AI_TOOL_CATEGORIES_MAP',
  AI_TOOL_PRICE_MAP = 'AI_TOOL_CATEGORIES_PRICE_MAP',
  AI_TOOL_PLATFORM_MAP = 'AI_TOOL_PLATFORM_MAP',
}
